#!/bin/sh

# Copyright 2015-2018 Joel Allen Luellwitz, Andrew Klapp and Brittney
# Scaccia.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Default Linux user and group information
GPGMAILER_USER='gpgmailer'
GPGMAILER_USER_COMMENT='GPG Mailer Daemon'
GPGMAILER_GROUP='gpgmailer'

case "$1" in
    configure)

    # Add the gpgmailer group
    if ! getent group "$GPGMAILER_GROUP" >> /dev/null; then
        echo -n "Adding group $GPGMAILER_GROUP..."
        addgroup --quiet --system "$GPGMAILER_GROUP" 2> /dev/null
        echo "done"
    fi

    # Add the gpgmailer user
    if ! getent passwd "$GPGMAILER_USER" >> /dev/null; then
        echo -n "Adding system user $GPGMAILER_USER..."
        adduser --quiet --system --ingroup "$GPGMAILER_GROUP" --no-create-home \
            --disabled-password "$GPGMAILER_USER" 2> /dev/null
        echo "done"
    fi

    # Adjust the user regardless of whether this script created the user or not.
    #   (The user might already exist.)
    usermod -c "$GPGMAILER_USER_COMMENT" -d "/nonexistent" -g "$GPGMAILER_GROUP" \
        "$GPGMAILER_USER"
    ;;
esac

# These are just here to help the admin out of bit. Failure isn't a big deal.
chown -R "$GPGMAILER_USER:$GPGMAILER_GROUP" /etc/gpgmailer/gnupg 2> /dev/null
chmod o-rwx /etc/gpgmailer/gnupg 2> /dev/null

update-rc.d gpgmailer defaults || exit 1
invoke-rc.d gpgmailer start || exit 1
